file(INSTALL
    "${CMAKE_CURRENT_LIST_DIR}/sitecustomize.py"
    DESTINATION "${CURRENT_PACKAGES_DIR}/tools/python3/Lib")

file(INSTALL "${VCPKG_ROOT_DIR}/LICENSE.txt" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)
