name: Setup Vcpkg
description: Initialize vcpkg tool, does not checkout the registry
  # TODO, set VCPKG_BASE_VERSION based on this
  # inputs:
  #  vcpkg-version:
  #    description: Enter vcpkg version tag or stable or latest
  #    required: false
  #    default: latest
  #    type: string

runs:
  using: composite
  steps:
    - name: Setup vcpkg
      if: runner.os != 'Windows'
      shell: bash
      run: |
        . <(curl https://aka.ms/vcpkg-init.sh -L)
        echo "PATH=$VCPKG_ROOT;$PATH" >> $GITHUB_ENV
        # osx dynamic fix, bandaid until next vcpkg tool release
        wget https://raw.githubusercontent.com/microsoft/vcpkg/9558037875497b9db8cf38fcd7db68ec661bffe7/scripts/cmake/z_vcpkg_fixup_rpath_macho.cmake -O ${VCPKG_ROOT}/scripts/cmake/z_vcpkg_fixup_rpath_macho.cmake

    - name: Setup vcpkg
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        iex (iwr -useb https://aka.ms/vcpkg-init.ps1)
        echo "PATH=$env:VCPKG_ROOT;$env:PATH" >> $env:GITHUB_ENV
