name: Auto update version db

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format_and_update_ports:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Setup vcpkg
        uses: ./.github/actions/setup-vcpkg

      - name: Format vcpkg.json
        run: |
          vcpkg format-manifest --all $(find . -name "vcpkg.json")

      - name: Open PR for vcpkg.json formatting
        id: format-pr
        if: success()
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: 'ci: format vcpkg configuration'
          title: 'ci: format vcpkg configuration'
          body: 'Automated formatting of `vcpkg.json` files via `vcpkg format-manifest`.'
          branch: create-pull-request/format-vcpkg-json
          delete-branch: true
          add-paths: |
            **/vcpkg.json

      - name: Exit 1 if vcpkg configuration changes have been detected
        if: steps.format-pr.outputs.pull-request-operation != ''
        run: |
          exit 1

      - name: Detect ports changes against default branch
        id: filter-ports
        uses: dorny/paths-filter@v3
        with:
          list-files: shell
          filters: |
            ports:
              - ports/**

      - name: Update versions
        if: steps.filter-ports.outputs.ports == 'true'
        run: |
          for dir in ports/* ; do
            vcpkg x-add-version ${dir##ports/} --overlay-ports=./ports \
              --x-builtin-registry-versions-dir=./versions/ \
              --x-builtin-ports-root=./ports
          done

      - name: Detect versions changes against local
        if: steps.filter-ports.outputs.ports == 'true'
        id: filter-versions
        uses: dorny/paths-filter@v3
        with:
          list-files: shell
          base: HEAD
          filters: |
            versions:
              - versions/**

      - name: Get last commit message
        if: steps.filter-versions.outputs.versions == 'true'
        id: last-commit-message
        run: |
          echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Open PR for versions update
        if: steps.filter-versions.outputs.versions == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update versions.db
          title: Update versions.db
          body: |
            Automated update of `versions/` triggered by:
            > ${{ steps.last-commit-message.outputs.msg }}
          branch: create-pull-request/update-versions-db
          delete-branch: true
          add-paths: versions/**
