---
name: 🪟 Windows
on:
  push:
    branches:
      - main
      - create-pull-request/**
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build (windows)
    runs-on: windows-2022
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - triplet: 'x64-windows'

    steps:
      - name: 🐣 Checkout
        uses: actions/checkout@v6

      - name: 🐩 Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: 🧽 Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@v1

      - name: 🐕 Checkout vcpkg
        uses: actions/checkout@v6
        with:
          repository: microsoft/vcpkg
          ref: efa4634bd526b87559684607d2cbbdeeec0f07d8 # TODO: can we have a canonical baseline for tests?
          path: vcpkg
          fetch-depth: 1

      - name: 🐾 Bootstrap vcpkg
        shell: bash
        run: |
          PKG_SOURCE_USER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
          ./vcpkg/bootstrap-vcpkg.sh
          NUGET_EXE=$(./vcpkg/vcpkg fetch nuget)
          echo "Downloaded $NUGET_EXE"
          $NUGET_EXE sources add -Name ghpkg -Source "https://nuget.pkg.github.com/$PKG_SOURCE_USER/index.json" -UserName "$PKG_SOURCE_USER" -Password "${{ secrets.GITHUB_TOKEN }}" -StorePasswordInClearText
          $NUGET_EXE setapikey "${{ secrets.GITHUB_TOKEN }}" -Source "https://nuget.pkg.github.com/$PKG_SOURCE_USER/index.json"
          echo "VCPKG_BINARY_SOURCES=clear;nuget,https://nuget.pkg.github.com/$PKG_SOURCE_USER/index.json,readwrite" >> $GITHUB_ENV
          VCPKG_ROOT=$(cygpath -w $(pwd)/vcpkg)
          echo "$VCPKG_ROOT" >> $GITHUB_PATH
          echo "VCPKG_ROOT=$VCPKG_ROOT" >> $GITHUB_ENV


      - name: 🌋 Build
        shell: bash
        run: |
            VCPKG_OPTIONS="--overlay-ports=${{ github.workspace }}/ports --triplet=${{ matrix.triplet }} --x-buildtrees-root=C:/vcpkg-build"
            ./vcpkg/vcpkg.exe install \
            $VCPKG_OPTIONS \
            'py-pyqt6[qtdeclarative,qt3d]' \
            py-pyyaml \
            py-numpy \
            gdal[python] \
            py-qscintilla \
            py-psycopg \
            py-psycopg2 \
            py-urllib3 \
            py-markupsafe \
            py-requests \
            py-isort \
            py-autopep8 \
            py-flask \
            py-ephem \
            py-geographiclib \
            py-kerberos-proxy-auth \
            py-pip-system-certs \
            py-requests-kerberos \
            py-wrapt \
            py-waitress \
            py-duckdb

            ./vcpkg/vcpkg.exe install $VCPKG_OPTIONS py-attrs
            ./vcpkg/vcpkg.exe install $VCPKG_OPTIONS py-beautifulsoup4
            ./vcpkg/vcpkg.exe install $VCPKG_OPTIONS py-fiona
            ./vcpkg/vcpkg.exe install $VCPKG_OPTIONS py-rasterio
            ./vcpkg/vcpkg.exe install $VCPKG_OPTIONS py-shapely
            # ./vcpkg/vcpkg.exe install $VCPKG_OPTIONS py-jsonschema
            ./vcpkg/vcpkg.exe install $VCPKG_OPTIONS py-networkx
            ./vcpkg/vcpkg.exe install $VCPKG_OPTIONS py-pyproj
            ./vcpkg/vcpkg.exe install $VCPKG_OPTIONS py-scipy
            ./vcpkg/vcpkg.exe install $VCPKG_OPTIONS py-matplotlib
            ./vcpkg/vcpkg.exe install $VCPKG_OPTIONS 'arrow[acero,compute,core,csv,dataset,example,filesystem,flight,flightsql,gcs,json,mimalloc,orc,parquet,s3,python]'

            # py-pydantic   fails with ERROR: truststore not available

      - name: 📑 Upload logs
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: logs-${{ matrix.triplet }}
          path: C:/vcpkg-build/**/*.log
